---
- name: deploy-bank-system-container
  hosts: ansible_clients
  become: true

  tasks: 
    - name: Install docker-py 
      pip:
        name: docker-py
        state: forcereinstall
    - name: Start Container 
      docker_container:
        name: banksystem
        image: "saksman3/banksystem:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8000:8000